# Generated by Django 6.0.3 on 2026-03-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0003_produittest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProduitTest',
        ),
    ]
